server:
  port: 8262
spring:
  application:
    name: servicediscover
eureka:
  instance:
    hostname: sdpeer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://chain:123456@sdpeer1:8260/eureka, http://chain:123456@sdpeer3:8263/eureka
       
